// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeKkAPruFxurNazCyDixK6d07sNnWwFnU',
    appId: '1:157338247439:ios:6d81784cf7ef2c97089e7a',
    messagingSenderId: '157338247439',
    projectId: 'studybuddy-e8dba',
    storageBucket: 'studybuddy-e8dba.firebasestorage.app',
    iosBundleId: 'com.example.studyBuddy',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_kk9plL6mvmRWwgDicjzJLyhlnQ3gdzM',
    appId: '1:157338247439:android:6e54ab2d749eb1db089e7a',
    messagingSenderId: '157338247439',
    projectId: 'studybuddy-e8dba',
    storageBucket: 'studybuddy-e8dba.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjYQbgTUhhBj2hIdB7afZJMjmMEbSxfaI',
    appId: '1:157338247439:web:a1e1b0fe95cbaa26089e7a',
    messagingSenderId: '157338247439',
    projectId: 'studybuddy-e8dba',
    authDomain: 'studybuddy-e8dba.firebaseapp.com',
    storageBucket: 'studybuddy-e8dba.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeKkAPruFxurNazCyDixK6d07sNnWwFnU',
    appId: '1:157338247439:ios:6d81784cf7ef2c97089e7a',
    messagingSenderId: '157338247439',
    projectId: 'studybuddy-e8dba',
    storageBucket: 'studybuddy-e8dba.firebasestorage.app',
    iosBundleId: 'com.example.studyBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjYQbgTUhhBj2hIdB7afZJMjmMEbSxfaI',
    appId: '1:157338247439:web:cf0a388afe31843c089e7a',
    messagingSenderId: '157338247439',
    projectId: 'studybuddy-e8dba',
    authDomain: 'studybuddy-e8dba.firebaseapp.com',
    storageBucket: 'studybuddy-e8dba.firebasestorage.app',
  );

}